PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
   ?subject core:subjectAreaOf PERSON_URI .
   ?vcard core:hasSubjectArea ?subject
} WHERE {
   PERSON_URI obo:ARG_2000028 ?vcard .
   ?vcard core:hasSubjectArea ?subject .
}
