PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>


CONSTRUCT {
     PERSON_URI obo:ARG_2000028 ?vcard .
     ?vcard obo:ARG_2000029 PERSON_URI .
     ?vcard rdf:type vcard:Individual
} WHERE {
     PERSON_URI obo:ARG_2000028 ?vcard .
}
